"""create_initial_tables

Revision ID: ab4e89b006ad
Revises: 
Create Date: 2026-05-28 01:44:42.048782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4e89b006ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_categories_category_id'), 'blog_categories', ['category_id'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_ref', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('complaint', sa.String(), nullable=True),
    sa.Column('service_id', sa.String(), nullable=True),
    sa.Column('doctor_id', sa.String(), nullable=True),
    sa.Column('package_id', sa.String(), nullable=True),
    sa.Column('visit_type', sa.String(length=20), nullable=False),
    sa.Column('selected_date', sa.String(length=20), nullable=False),
    sa.Column('selected_time', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_ref'), 'bookings', ['booking_ref'], unique=True)
    op.create_table('cms_doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=True),
    sa.Column('experience', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('reviews_count', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('education', sa.String(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('available_days', sa.JSON(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('specializations', sa.JSON(), nullable=True),
    sa.Column('achievements', sa.JSON(), nullable=True),
    sa.Column('consultation_fee', sa.String(), nullable=True),
    sa.Column('reviews', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_doctors_doctor_id'), 'cms_doctors', ['doctor_id'], unique=True)
    op.create_table('cms_home',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hero', sa.JSON(), nullable=False),
    sa.Column('why_us', sa.JSON(), nullable=False),
    sa.Column('cta', sa.JSON(), nullable=False),
    sa.Column('trust_bar', sa.JSON(), nullable=False),
    sa.Column('testimonials', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('original_price', sa.Integer(), nullable=True),
    sa.Column('badge', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('preparation', sa.JSON(), nullable=True),
    sa.Column('includes', sa.JSON(), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_packages_package_id'), 'cms_packages', ['package_id'], unique=True)
    op.create_table('cms_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tagline', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('long_description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('accent_color', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('hero_image', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('procedures', sa.JSON(), nullable=True),
    sa.Column('prices', sa.JSON(), nullable=True),
    sa.Column('doctors', sa.JSON(), nullable=True),
    sa.Column('faqs', sa.JSON(), nullable=True),
    sa.Column('related_services', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_services_service_id'), 'cms_services', ['service_id'], unique=True)
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('blog_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('excerpt', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('author_role', sa.String(), nullable=True),
    sa.Column('author_image', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('read_time', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['blog_categories.category_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_post_id'), 'blog_posts', ['post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_posts_post_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_cms_services_service_id'), table_name='cms_services')
    op.drop_table('cms_services')
    op.drop_index(op.f('ix_cms_packages_package_id'), table_name='cms_packages')
    op.drop_table('cms_packages')
    op.drop_table('cms_home')
    op.drop_index(op.f('ix_cms_doctors_doctor_id'), table_name='cms_doctors')
    op.drop_table('cms_doctors')
    op.drop_index(op.f('ix_bookings_booking_ref'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_blog_categories_category_id'), table_name='blog_categories')
    op.drop_table('blog_categories')
    # ### end Alembic commands ###
