"""Add FAQ models

Revision ID: ac87cad76f2e
Revises: 6d21c9cd13fd
Create Date: 2026-06-10 21:23:52.004939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac87cad76f2e'
down_revision: Union[str, Sequence[str], None] = '6d21c9cd13fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_categories_id'), 'faq_categories', ['id'], unique=False)
    
    op.create_table('faq_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['faq_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_items_category'), 'faq_items', ['category'], unique=False)
    op.create_index(op.f('ix_faq_items_id'), 'faq_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faq_items_id'), table_name='faq_items')
    op.drop_index(op.f('ix_faq_items_category'), table_name='faq_items')
    op.drop_table('faq_items')
    op.drop_index(op.f('ix_faq_categories_id'), table_name='faq_categories')
    op.drop_table('faq_categories')
    # ### end Alembic commands ###
